debug: true
org:
    makkiato:
        arcadedb:
            connection:
                host: localhost
                port: 2480
                database: testdb
                username: root
                password: playwithdata
                leader-preferred: true

logging:
    level:
        org:
            springframework: INFO

management:
  endpoints:
    web:
        exposure:
            include: "*"
    jmx:
        exposure:
            include: "*"

spring:
    threads:
        virtual:
            enabled: true