version: '3.8'
services:
  devcontainer:
    env_file: devcontainer.env
    image: maven:3.9.6-sapmachine-21
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: gfinger/arcadedb-local:24.2.1
    restart: unless-stopped

    